// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtGfqOZ_1j0XSV3_2HEFVdGS9nvcMPS18',
    appId: '1:83358031084:web:8e95f0e3e4da70fe83d9c9',
    messagingSenderId: '83358031084',
    projectId: 'je-le-apps-test-task',
    authDomain: 'je-le-apps-test-task.firebaseapp.com',
    storageBucket: 'je-le-apps-test-task.appspot.com',
    measurementId: 'G-7X03NWX0BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1N_70NpHYglODPhAXOM-aUIVTvb7z-rY',
    appId: '1:83358031084:android:c142de270ebaca4483d9c9',
    messagingSenderId: '83358031084',
    projectId: 'je-le-apps-test-task',
    storageBucket: 'je-le-apps-test-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYX0T7jOxqKN41dIeB5CL2p29q8XqlCY',
    appId: '1:83358031084:ios:938bc32d2e26122583d9c9',
    messagingSenderId: '83358031084',
    projectId: 'je-le-apps-test-task',
    storageBucket: 'je-le-apps-test-task.appspot.com',
    iosBundleId: 'com.example.jeleAppsTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKYX0T7jOxqKN41dIeB5CL2p29q8XqlCY',
    appId: '1:83358031084:ios:938bc32d2e26122583d9c9',
    messagingSenderId: '83358031084',
    projectId: 'je-le-apps-test-task',
    storageBucket: 'je-le-apps-test-task.appspot.com',
    iosBundleId: 'com.example.jeleAppsTestTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtGfqOZ_1j0XSV3_2HEFVdGS9nvcMPS18',
    appId: '1:83358031084:web:5a293a4ea68693ee83d9c9',
    messagingSenderId: '83358031084',
    projectId: 'je-le-apps-test-task',
    authDomain: 'je-le-apps-test-task.firebaseapp.com',
    storageBucket: 'je-le-apps-test-task.appspot.com',
    measurementId: 'G-6ZKDC52335',
  );
}
